var assert = require('assert')
  , irc = require('../../lib/irc');

function check(code, data, expected) {
  var r = irc.replies[code];
  assert.notEqual(undefined, r, 'reply ' + code + ' should be defined');
  assert.equal(expected, r.template(data));
}

check(401, {nick:'foo'}, "foo :No such nick/channel");
check(402, {server:'foo'}, "foo :No such server");
check(403, {channel:'foo'}, "foo :No such channel");
check(404, {channel:'foo'}, "foo :Cannot send to channel");
check(405, {channel:'foo'}, "foo :You have joined too many channels");
check(406, {nick:'foo'}, "foo :There was no such nickname");
check(407, {target:'foo'}, "foo :Duplicate recipients. No message delivered");
check(409, {}, ":No origin specified");
check(411, {command:'foo'}, ":No recipient given (foo)");
check(412, {}, ":No text to send");
check(413, {hostmask:'foo'}, "foo :No toplevel domain specified");
check(414, {hostmask:'foo'}, "foo :Wildcard in toplevel domain");
check(421, {command:'foo'}, "foo :Unknown command");
check(422, {}, ":MOTD File is missing");
check(423, {server:'foo'}, "foo :No administrative info available");
check(424, {fileop:'foo', file:'bar'}, ":File error doing foo on bar");
check(431, {}, ":No nickname given");
check(432, {nick:'foo'}, "foo :Erroneus nickname");
check(433, {nick:'foo'}, "foo :Nickname is already in use");
check(436, {nick:'foo'}, "foo :Nickname collision KILL");
check(441, {nick:'foo', channel:'bar'}, "foo bar :They aren't on that channel");
check(442, {channel:'foo'}, "foo :You're not on that channel");
check(443, {user:'foo', channel:'bar'}, "foo bar :is already on channel");
check(444, {user:'foo'}, "foo :User not logged in");
check(445, {}, ":SUMMON has been disabled");
check(446, {}, ":USERS has been disabled");
check(451, {}, ":You have not registered");
check(461, {command:'foo'}, "foo :Not enough parameters");
check(462, {}, ":You may not reregister");
check(463, {}, ":Your host isn't among the privileged");
check(464, {}, ":Password incorrect");
check(465, {}, ":You are banned from this server");
check(467, {channel:'foo'}, "foo :Channel key already set");
check(471, {channel:'foo'}, "foo :Cannot join channel (+l)");
check(472, {mode:'foo'}, "foo :is unknown mode char to me");
check(473, {channel:'foo'}, "foo :Cannot join channel (+i)");
check(474, {channel:'foo'}, "foo :Cannot join channel (+b)");
check(475, {channel:'foo'}, "foo :Cannot join channel (+k)");
check(481, {}, ":Permission Denied- You're not an IRC operator");
check(482, {channel:'foo'}, "foo :You're not channel operator");
check(483, {}, ":You cant kill a server!");
check(491, {}, ":No O-lines for your host");
check(501, {}, ":Unknown MODE flag");
check(502, {}, ":Cant change mode for other users");
check(302, {replies:'foo'}, ":foo");
check(303, {nicks:'foo'}, ":foo");
check(301, {nick:'foo', message:'bar'}, "foo :bar");
check(305, {}, ":You are no longer marked as being away");
check(306, {}, ":You have been marked as being away");
check(311, {nick:'foo', user:'bar', host:'baz', realname:'biff'}, "foo bar baz * :biff");
check(312, {nick:'foo', server:'bar', serverinfo:'baz'}, "foo bar :baz");
check(313, {nick:'foo'}, "foo :is an IRC operator");
check(317, {nick:'foo', idle:'bar'}, "foo bar :seconds idle");
check(318, {nick:'foo'}, "foo :End of /WHOIS list");
check(319, {nick:'foo', channel:'bar'}, "foo :bar");
check(314, {nick:'foo', user:'bar', host:'baz', realname:'biff'}, "foo bar baz * :biff");
check(369, {nick:'foo'}, "foo :End of WHOWAS");
check(321, {}, "Channel :Users  Name");
check(322, {channel:'foo', count:'bar'}, "foo bar :");
check(323, {}, ":End of /LIST");
check(324, {channel:'foo', mode:'bar', params:'baz'}, "foo bar baz");
check(331, {channel:'foo'}, "foo :No topic is set");
check(332, {channel:'foo', topic:'bar'}, "foo :bar");
check(341, {channel:'foo', nick:'bar'}, "foo bar");
check(342, {user:'foo'}, "foo :Summoning user to IRC");
check(351, {version:'foo', server:'bar', comments:'baz'}, "foo bar :baz");
check(352, {channel:'foo', user:'bar', host:'baz', server:'biff', nick:'qux', mode:'xyzzy', hopcount:'plugh', realname:'phuce'}, "foo bar baz biff qux xyzzy :plugh phuce");
check(315, {name:'foo'}, "foo :End of /WHO list");
check(353, {channel:'foo', nicks:'bar'}, "@ foo :bar");
check(366, {channel:'foo'}, "foo :End of /NAMES list");
check(364, {hostmask:'foo', server:'bar', hopcount:'baz', serverinfo:'biff'}, "foo bar :baz biff");
check(365, {hostmask:'foo'}, "foo :End of /LINKS list");
check(367, {channel:'foo', banid:'bar'}, "foo bar");
check(368, {channel:'foo'}, "foo :End of channel ban list");
check(371, {info:'foo'}, ":foo");
check(374, {}, ":End of /INFO list");
check(375, {server:'foo'}, ":- foo Message of the day - ");
check(372, {motd:'foo'}, ":- foo");
check(376, {}, ":End of /MOTD command");
check(381, {}, ":You are now an IRC operator");
check(382, {}, " :Rehashing");
check(391, {server:'foo', time:'bar'}, "foo :bar");
check(392, {}, ":UserID   Terminal  Host");
check(393, {user:'foo', tty:'bar', host:'baz'}, ":foo bar baz");
check(394, {}, ":End of users");
check(395, {}, ":Nobody logged in");
check(200, {version:'foo', destination:'bar', next:'baz'}, "Link foo bar baz");
check(201, {cls:'foo', server:'bar'}, "Try. foo bar");
check(202, {cls:'foo', server:'bar'}, "H.S. foo bar");
check(203, {cls:'foo', ip:'bar'}, "???? foo bar");
check(204, {cls:'foo', nick:'bar'}, "Oper foo bar");
check(205, {cls:'foo', nick:'bar'}, "User foo bar");
check(206, {cls:'foo', s:'bar', c:'baz', server:'biff', hostmask:'qux'}, "Serv foo barS bazC biff qux");
check(208, {type:'foo', name:'bar'}, "foo 0 bar");
check(261, {log:'foo', debuglevel:'bar'}, "File foo bar");
check(211, {name:'foo', sendQueue:'bar', sentMessages:'baz', sentBytes:'biff', receivedMessages:'xyzzy', receivedBytes:'plugh', uptime:'phuce'}, "foo bar baz biff xyzzy plugh phuce");
check(212, {command:'foo', count:'bar'}, "foo bar");
check(213, {host:'foo', name:'bar', port:'baz', cls:'biff'}, "C foo * bar baz biff");
check(214, {host:'foo', name:'bar', port:'baz', cls:'biff'}, "N foo * bar baz biff");
check(215, {host:'foo', host2:'bar', port:'baz', cls:'biff'}, "I foo * bar baz biff");
check(216, {host:'foo', user:'bar', port:'baz', cls:'biff'}, "K foo * bar baz biff");
check(218, {cls:'foo', pingFrequency:'bar', connectFrequency:'baz', maxSendQueue:'biff'}, "Y foo bar baz biff");
check(219, {letter:'foo'}, "foo :End of /STATS report");
check(241, {hostmask:'foo', server:'bar', maxDepth:'baz'}, "L foo * bar baz");
check(242, {days:'foo', hours:'bar', minutes:'baz', seconds:'biff'}, ":Server Up foo days bar:baz:biff");
check(243, {hostmask:'foo', name:'bar'}, "O foo * bar");
check(244, {hostmask:'foo', server:'bar'}, "H foo * bar");
check(221, {mode:'foo'}, "foo");
check(251, {userCount:'foo', invisibleCount:'bar', serverCount:'baz'}, ":There are foo users and bar invisible on baz servers");
check(252, {count:'foo'}, "foo :operator(s) online");
check(253, {count:'foo'}, "foo :unknown connection(s)");
check(254, {count:'foo'}, "foo :channels formed");
check(255, {clientCount:'foo', serverCount:'bar'}, ":I have foo clients and bar servers");
check(256, {server:'foo'}, "foo :Administrative info");
check(257, {location:'foo'}, ":foo");
check(258, {location:'foo'}, ":foo");
check(259, {email:'foo'}, ":foo");
